---

- include: check_vars.yml

- name: define distribution value for repository
  set_fact: >
    mysql_dist="{% if ansible_distribution == 'Amazon' %}6{% else %}{{ ansible_distribution_major_version }}{% endif %}"
  check_mode: no

- include: repo.yml

- name: install MySQL
  yum: pkg={{ item }} state=installed
  with_items:
    - mysql-community-client
    - mysql-community-server
    - mysql-community-libs

- name: install Python interface to MySQL
  yum: pkg=MySQL-python state=installed
  when: ansible_distribution == 'CentOS'

- name: install devel packages
  yum: pkg={{ item }} state=installed
  with_items:
    - gcc
    - python26-pip
    - python26-devel
    - mysql-community-devel
  when: ansible_distribution == 'Amazon'

- name: install Python interface to MySQL
  pip: name=mysqlclient state=present
  when: ansible_distribution == 'Amazon'

- name: copy my.cnf
  template: src=etc/my.cnf.j2 dest=/etc/my.cnf backup=yes
  notify: restart mysqld

- name: start the MySQL service
  service: name=mysqld state=started enabled=true

- include: secure-installation.yml
- include: users.yml
- include: replication.yml

- include: timezones.yml
  when: mysql_import_timezones
